"""update_story_and_node_for_start_node_logic

Revision ID: 001319d03f6f 
Revises: 4559d31f91b4 
Create Date: 2025-05-17 22:40:00.000000 # 이 파일의 실제 생성 시간으로 유지

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '001319d03f6f' 
down_revision: Union[str, None] = '4559d31f91b4' 

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NodeType Enum에 'START' 값 추가 (PostgreSQL 용)
    op.execute("ALTER TYPE nodetype ADD VALUE IF NOT EXISTS 'START'")
    print("Executed: ALTER TYPE nodetype ADD VALUE IF NOT EXISTS 'START'")
    
    # Story 테이블에서 start_node_id 컬럼 삭제 시도 부분은 주석 처리 또는 제거합니다.
    # 오류 로그에 따르면 해당 컬럼이 이미 존재하지 않으므로, 
    # 이 마이그레이션의 목표 중 하나(컬럼 제거)는 이미 달성된 상태입니다.
    # op.drop_column('stories', 'start_node_id')
    # print("Attempted/Skipped: Dropped column 'start_node_id' from 'stories' table (as it might be already gone).")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # start_node_id 컬럼을 upgrade에서 삭제하지 않았으므로, downgrade에서도 추가하지 않습니다.
    # 만약 이전 상태로 정확히 롤백하려면, 4559d31f91b4 마이그레이션의 상태를 기준으로 해야 합니다.
    # print("Info: 'start_node_id' column re-creation is not handled in this downgrade as its drop was skipped/already done.")

    # NodeType Enum에서 'START' 값을 제거하는 것은 일반적으로 downgrade에서 잘 하지 않습니다.
    print("Info: Downgrade for 'START' value in nodetype enum is not automatically handled here and is generally not recommended.")
    
    # ### end Alembic commands ###
